apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
  labels:
    app: your-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app-container
          image: sybbb/cicd:v1-20241223162326-6450
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"

