apiVersion: v1
kind: Service
metadata:
  name: your-app-service
  labels:
    app: your-app
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # 외부 트래픽을 받을 경우 사용

